feat: map ordering query parameter to correct value
ICATT-Menselijk-Digitaal/podiumd-adapter pull request #45
Opened 2024-07-18 13:02 UTC by felixcicatt

Part of [PC-304](https://dimpact.atlassian.net/browse/PC-304)

2024-07-24 07:57 UTC, mstokericatt requested changes

2024-07-24 11:44 UTC, felixcicatt commented on test/PodiumdAdapter.Web.Test/GetZakenTests.cs
> +            // if we get an ok, the mock http message handler has received the expected call
Ja. Maar ik zie dat er ook een explicietere manier is om dit te checken, met `VerifyNoOutstandingExpectation`. Die heb ik nu gebruikt.

2024-08-01 11:45 UTC, mstokericatt commented on test/PodiumdAdapter.Web.Test/GetZakenTests.cs
> +            // if we get an ok, the mock http message handler has received the expected call
test: 
comment resolved by commit 7a863b3e7e8673a67378745691ff8d35927b9ae6

2024-08-01 11:51 UTC, mstokericatt approved these changes

2024-08-06 07:48 UTC, merged